from flask import Flask, request, redirect, render_template, send_from_directory
import pathlib
from werkzeug.utils import secure_filename
import os

app = Flask(__name__)

# Paths configuration
UPLOAD_FOLDER = 'uploads/'
ALLOWED_EXTENSTIONS = {'.png', '.jpg', '.jpeg'}
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

# Check the received file
def allowed_file(filename):
    file_extension = pathlib.Path(filename).suffix.lower()
    return file_extension in ALLOWED_EXTENSTIONS

@app.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        # Check if file is send
        if 'image' not in request.files:
            return redirect(request.url)
        
        file = request.files['image']

        # Check if no file was selected
        if file.filename == '':
            return redirect(request.url)
        
        # Check if file has correct ext
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            file.save(filepath)

            description = "This is a sample description generated by the AI model."
            return render_template('index.html', uploaded_image=filename, description=description)
    
    return render_template('index.html')

# Path to download uploaded files
@app.route('/uploads/<filename>')
def uploaded_file(filename):
    return send_from_directory(app.config['UPLOAD_FOLDER'], filename)

if __name__ == '__main__':
    os.makedirs(UPLOAD_FOLDER, exist_ok=True)
    app.run(debug=True)


        

    